from django.db import models

# class Orders(models.Model):

#     # Material Drop Down Options

#     class PlateDepartment(models.TextChoices):
#         'HRPL' = 'ASTM A-36 PLATE/HOT ROLL PLATE(CAN’T ANNEAL)'
#         'HRPLCQ' = 'HOT ROLL QC PLATE'
#         'A36D' = 'A-36 DOMESTIC'
#         'QC15' = 'QUICK CUT 15'
#         'QC20' = 'QUICK CUT 20'
#         'QC45' = 'QUICK CUT 45'
#         '45PL' = '1045 PLATE (ANNEAL)'
#         '514x' = 'A514 GRADE (x= B,E,F,H,P,Q,R,S) / T-1'
#         '1015' = '1015 HR PLATE'
#         '1020' = '1020 HR PLATE'
#         '106P' = '1060 PLATE'
#         '41AP' = '4140 AS ROLLED PLATE (ANNEAL OR HT TO)'
#         '43PL' = '4340 AS ROLLED PLATE (ANNEAL)'
#         '516P' = 'A516 PLATE (DO NOT ANNEAL)'
#         '5720' = 'A572 PLATE GRADE 50 / A709 GR 50'
#         '57265' = 'A572 PLATE GRADE 65'
#         '588P' = 'ASTM A-588 HR PLATE / A709 GR 50W'
#         'AR400PL' = 'AR400 PLATE'
#         'AR500PL' = 'AR500 PLATE'
#         'FLPL' = 'FLOOR PLATE'
#         'HRSHxxGA' = 'HR GAGE PLATE (x=10,11,12,ETC.)'
#         'HRPO' = 'HR PICKLED & OILED'
#         '5720xxMM' = '572 MM PLATE (x=16,20,ETC.)'

#     class BarToolDepartment(models.TextChoices):
#         'HRBA' = 'HR BAR'
#         'HRS' = 'HR SQUARE'
#         'HRRD' = 'HR ROUND'
#         '101H' = '1018 HR ROUND'
#         'CRF' = 'COLD ROLL FLAT'
#         'CRR' = 'COLD ROLL ROUND'
#         'CRS' = 'COLD ROLL SQUARE'
#         '41BA' = '4140 BAR'
#         '41AR' = '4140 ANNEALED ROUNDS'
#         '41DA' = '4140 DCF ANNEALED'
#         '41DAP' = '4140 DCF ANNEALED (NON -STANDARD)'
#         '41PL' = '4140 DCF PRE HARD (NON-STANDARD)'
#         '41HR' = '4140 HT REDI-CUT ROUNDS'
#         '41FG' = 'FLAT GROUND'
#         'A2BA' = 'A-2 BAR'
#         'A2RD' = 'A-2 ROUND'
#         'A2PL' = 'A-2 PLATE'
#         'A2FG' = 'PREC. FLAT GROUND'
#         'A2FO' = 'OVERSIZED FLAT GROUND'
#         'D2BA' = 'D-2 WEAR DIE BAR'
#         'D2RD' = 'D-2 WEAR DIE ROUND'
#         'D2PL' = 'D-2 PLATE'
#         'D2FG' = 'D-2 PREC. FLAT GROUND'
#         'D2FO' = 'D-2 OVERSIZED FLAT GROUND'
#         'T' = 'TUBE SQUARE'
#         'TB' = 'TUBE RECTANGLE (LARGER SIZE FIRST)'
#         'AN' = 'ANGLE (EX: 2X2X1/4X 40\' = AN03203204)'
#         'BWF' = 'WIDE FLANGE BEAM'
#         'CH' = 'STRUCTURAL CHANNEL'
#         '101H' = '1018 HR ROUND'
#         '86PL' = '8620 PLATE'
#         '8620' = '8620 ROUNDS'
#         '6061' = '6061 ALUMINUM SHEET'
#         '61BA' = '6061 ALUMINUM BAR'
#         '61RD' = '6061 ALUMINUM ROUND'
#         '61S' = '6061 ALUMINUM SQUARE'
#         'TGP' = '1045 TG&P ROUNDS'
#         'ALTP' = 'CAST TOOL PLATE'
#         'S7BA' = 'S-7 BAR'
#         'S7RD' = 'S-7 ROUND'
#         'S7PL' = 'S-7 PLATE'
#         'H13R' = 'H-13 ROUND'
#         'H13P' = 'H-13 PLATE'
#         'TD' = 'DOM TUBE'
#         'O1BA' = 'O-1 BAR'
#         'O1RD' = 'O-1 ROUND'
#         'O1PL' = 'O-1 PLATE'
#         'O1FG' = 'O-1 FLAT GROUND'
#         'O1FO' = 'O-1 OVERSIZED FLAT GROUND'
#         'BS' = 'STANDARD I-BEAM'
#         'T1PL' = 'T-1 PLATE'
#         'CDST' = 'CD STRESSPROOF'
#         '304P' = '304 STAINLESS STEEL PLATE'
#         '304R' = '304 STAINLESS STEEL ROUND'
